alias Rentaj.Repo
alias Rentaj.Items.Item

%Item{name: "Item 1", category_id: 1, user_id: 1, description: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.", price_per_day: 10, pick_up: true, delivery: false, capara: 80.00, active: true } |> Repo.insert!()
%Item{name: "Item 2", category_id: 2, user_id: 1, description: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.", price_per_day: 10, pick_up: true, delivery: true, capara: 100.00, active: false } |> Repo.insert!()
%Item{name: "Item 3", category_id: 3, user_id: 1, description: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.", price_per_day: 10, pick_up: true, delivery: false, capara: 20.00, active: true } |> Repo.insert!()
%Item{name: "Item 4", category_id: 3, user_id: 1, description: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.", price_per_day: 10, pick_up: false, delivery: false, capara: 40.00, active: true } |> Repo.insert!()
%Item{name: "Item 5", category_id: 3, user_id: 2, description: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.", price_per_day: 10, pick_up: true, delivery: false, capara: 50.00, active: false } |> Repo.insert!()
%Item{name: "Item 5", category_id: 4, user_id: 2, description: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.", price_per_day: 10, pick_up: true, delivery: true, capara: 90.00, active: true } |> Repo.insert!()
%Item{name: "Item 6", category_id: 4, user_id: 3, description: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.", price_per_day: 10, pick_up: true, delivery: false, capara: nil, active: false} |> Repo.insert!()
%Item{name: "Item 7", category_id: 4, user_id: 3, description: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.", price_per_day: 10, pick_up: true, delivery: false, capara: 280.00, active: true } |> Repo.insert!()
%Item{name: "Item 8", category_id: 6, user_id: 3, description: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.", price_per_day: 10, pick_up: false, delivery: true, capara: 380.00, active: true } |> Repo.insert!()
%Item{name: "Item 9", category_id: 8, user_id: 4, description: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.", price_per_day: 10, pick_up: true, delivery: false, capara: nil, active: false } |> Repo.insert!()
%Item{name: "Item 10", category_id: 9, user_id: 5,description: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.", price_per_day: 10, pick_up: true, delivery: false, capara: 8.00, active: false } |> Repo.insert!()
%Item{name: "Item 11", category_id: 9, user_id: 6, description: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.", price_per_day: 10, pick_up: false, delivery: false, capara: 10.00, active: true } |> Repo.insert!()
%Item{name: "Item 12", category_id: 9, user_id: 6, description: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.", price_per_day: 10, pick_up: false, delivery: true, capara: 20.00, active: true } |> Repo.insert!()
%Item{name: "Item 13", category_id: 11, user_id: 6, description: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.", price_per_day: 10, pick_up: true, delivery: false, capara: 30.00, active: true } |> Repo.insert!()
%Item{name: "Item 14", category_id: 12, user_id: 6, description: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.", price_per_day: 10, pick_up: true, delivery: true, capara: 50.00, active: false } |> Repo.insert!()
